### ISSUE TITLE
Task: Logs

### ISSUE THREAD

**Issue by naviisml** [naviisml/laravel-phone-app#15]
**Description**
Add logging

**Tasks**

- [x] Make `logs` table
    - user_id: string, nullable
    - type: string
    - data: json
    - metadata: json, nullable
    - timestamps
- [x] Make `Logs` Model
- [x] Make `Logs` Factory (for testing purposes)
- [x] Make `LogsController`
- [x] Make `/logs` endpoint (Protected: For logged in users only)
    - [x] Make `Read/Get` endpoint (/logs/get/{type?})
    - [x] Make `Delete` endpoint (/logs/delete)
    - [x] Make tests for functions
- [x] Make Front-End table to show translations
    - [x] Delete a log
